name: Update MCP Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python backend/main.py

    - name: Commit and push updated data
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add backend/data/mcpverse_data.json
        git commit -m "🔄 Auto-update MCP repo data" || echo "No changes"
        git push
