name: Update MCP Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      OPENSEARCH_HOST: ${{ secrets.OPENSEARCH_HOST }}
      OPENSEARCH_PORT: ${{ secrets.OPENSEARCH_PORT }}
      OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
      OPENSEARCH_PASS: ${{ secrets.OPENSEARCH_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python backend/fetch_repos.py
    
    - name: Commit and push updated data
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add data/mcpverse_data.json
        git commit -m "🔄 Auto-update MCP repo data" || echo "No changes"
        git push

    - name: Run embedding and opensearch indexer
      run: python backend/embedder.py
